W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/bands')

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

  resources :notes, only: [:create, :destroy]
end

W5D1/music_app/app/models/note.rb
class Note < ApplicationRecord
  # N.B. Remember, Rails 5 automatically validates the presence of
  # belongs_to associations, so we can leave the validation of user and
  # track out here.
  validates :content, presence: true

  belongs_to :user
  belongs_to :track
end

W5D1/music_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user!

  def create
    note = current_user.notes.new(note_params)
    note.save
    flash[:errors] = note.errors.full_messages

    redirect_to track_url(note.track_id)
  end

  def destroy
    note = current_user.notes.find(params[:id])
    note.destroy
    redirect_to track_url(note.track_id)
  end

  private
  
  def note_params
    params.require(:note).permit(:content, :track_id)
  end
end

W5D1/music_app/app/helpers/notes_helper.rb
module NotesHelper
end

W5D1/music_app/app/views/note/_form.html.erb
<h4 class='sub-header'>New Note</h4>

<form class='form' action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">

  <p>
    <label for="note_content">Content</label>
    <textarea id="note_content"
      rows="7" cols="30"
      name="note[content]"></textarea>
  </p>

  <input type="submit">
</form>

W5D1/music_app/app/views/note/_note.html.erb
<div class='note-item'>
  <p><%= note.content %></p>
  <div class='note-item-info'>
    <p>Authored by: <%= note.user.email %></p>

    <% if note.user_id == current_user_id %>
      <form action="<%= note_url(note) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
        <input type="submit" value="Destroy Note">
      </form>
    <% end %>
  </div>
</div>